### ISSUE TITLE
C# conversion 

### ISSUE THREAD

**Issue by valadas** [DNNCommunity/DNN.Gallery#6]
## Describe the solution you'd like
Module should be converted to C#

**Comment by EPTamminga** [comment]
@valadas I could not build out of the box, missing the references. Had to find DNN 5.6.8 DLL's. Also, the Gallery.exif.dll file was not there. Had to go back to DNN 3 to find one.  I have done the conversion (see attached file), there are a number of errors in the result, probably due to the ambiguous guesswork of the converter.
[Gallery-CS.ZIP](https://github.com/DNNCommunity/DNN.Gallery/files/2195640/Gallery-CS.ZIP)

I do not have time left today to go through these issues, I have to go to a birthday of one of my grandchildren...

**Comment by valadas** [comment]
Thanks @EPTamminga I checked a couple errors on both and the errors are almost line per line the same ones :) I gonna continue with what I had since I already fixed a lot of them. But I will reference your version if it helps somewhere, but so far we have almost the same conversion errors...

**Comment by EPTamminga** [comment]
@valadas I think when the module was more current, the # of conversion errors/guesswork would have been less.

**Comment by valadas** [comment]
Ok, got it to build, but I have multiple errors, I will create individual issues for those errors
